# Generated by Django 3.0.5 on 2021-03-24 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mens_CasualShirt',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('ideal_for', multiselectfield.db.fields.MultiSelectField(max_length=200)),
                ('neck_type', models.CharField(max_length=100)),
                ('seleeve_type', models.CharField(choices=[('Half Sleeve', 'Half Sleeve'), ('Full Sleeve', 'Full Sleeve'), ('Short Sleeve', 'Short Sleeve'), ('3/4 Sleeve', '3/4 Sleeve'), ('Sleeveless', 'Sleeveless'), ('Roll-up Sleeve', 'Roll-up Sleeve')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', jsonfield.fields.JSONField()),
                ('fit', models.CharField(choices=[('Regular', 'Regular'), ('Slim', 'Slim'), ('Boxy', 'Boxy'), ('Super Slim', 'Super Slim'), ('Tailored', 'Tailored')], max_length=100)),
                ('return_policy', models.IntegerField()),
                ('cod', models.BooleanField()),
                ('image', jsonfield.fields.JSONField()),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mens_FormalShirt',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('ideal_for', jsonfield.fields.JSONField()),
                ('neck_type', models.CharField(max_length=100)),
                ('seleeve_type', models.CharField(choices=[('Half Sleeve', 'Half Sleeve'), ('Full Sleeve', 'Full Sleeve'), ('Short Sleeve', 'Short Sleeve'), ('3/4 Sleeve', '3/4 Sleeve'), ('Sleeveless', 'Sleeveless'), ('Roll-up Sleeve', 'Roll-up Sleeve')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fit', models.CharField(choices=[('Regular', 'Regular'), ('Slim', 'Slim'), ('Boxy', 'Boxy'), ('Super Slim', 'Super Slim'), ('Tailored', 'Tailored')], max_length=100)),
                ('size', jsonfield.fields.JSONField()),
                ('return_policy', models.IntegerField()),
                ('cod', models.BooleanField()),
                ('image', jsonfield.fields.JSONField()),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mens_Tshirt',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('ideal_for', multiselectfield.db.fields.MultiSelectField(choices=[('Mens', 'Mens')], max_length=4)),
                ('neck_type', models.CharField(max_length=100)),
                ('seleeve_type', models.CharField(choices=[('Full Sleeve', 'Full Sleeve'), ('Half Sleeve', 'Half Sleeve'), ('Sleeveless', 'Sleeveless'), ('Short Sleeve', 'Short Sleeve'), ('Layered Sleeve', 'Layered Sleeve'), ('Roll-up Sleeve', 'Roll-up Sleeve'), ('3/4 Sleeve', '3/4 Sleeve'), ('Raglan', 'Raglan')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=12)),
                ('return_policy', models.IntegerField()),
                ('cod', models.BooleanField()),
                ('image', jsonfield.fields.JSONField()),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mens_TshirtRatings',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.Mens_Tshirt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
                'index_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Mens_FormalShirtRatings',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.Mens_FormalShirt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
                'index_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Mens_CasualShirtRatings',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.Mens_CasualShirt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
                'index_together': {('user', 'product')},
            },
        ),
    ]
