# Generated by Django 3.0.5 on 2021-03-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mens_formalshirt',
            name='fit',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Slim', 'Slim'), ('Boxy', 'Boxy'), ('Super Slim', 'Super Slim'), ('Tailored', 'Tailored')], max_length=50),
        ),
    ]
