# Generated by Django 3.0.5 on 2021-03-25 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fashion', '0004_auto_20210324_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mens_tshirt',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
